name: CTF_2.1.0
main: com.random.captureTheFlag.Main
version: 2.1.0
api-version: 1.18
commands:
  ctfteams:
    usage: ""
  ctfhelp:
    usage: ""
  ctfsetup:
    usage: ""
  shout:
    usage: ""
  ctfstart:
    usage: ""
    aliases: ["ctfcancel"]
  ctfsettings:
    usage: ""
  ctfenable:
    usage: ""
    aliases: ["ctfdisable"]