name: CaptureTheFlag
main: com.random.captureTheFlag.Main
version: 2.0.1
api-version: 1.19
commands:
  teams:
    usage: ""
  ctfhelp:
    usage: ""
  setup:
    usage: ""
  shout:
    usage: ""
  start:
    usage: ""
    aliases: ["cancel"]
  settings:
    usage: ""
  enable:
    usage: ""
    aliases: ["un-enable"]